### ISSUE TITLE
[4fdeb39][model04_171201-1104.py] ValueError, expected input to have 4 dim, not (192, 1)

### ISSUE THREAD

**Issue by davisjazz** [davisjazz/SDC_PRJ03_Cloning#1]
**# REF :** 4fdeb39

**# SCENARIO :**
1.  [win10][cmd] activate keras 
2.  [win10][cmd] python model04_171201-1104.py

**# EXPECTED RESULT:**   
- successful compilation of the model
- generation of the model.h5 file, ready to be tested in the simulator

**# CURRENT RESULT:**
- Compilation failed. The following error message is displayed:
`ValueError: Error when checking input: expected lambda_1_input to have 4 dimensions, but got array with shape (192, 1)`

- More detailed traces, look the next comment.

**# ENVIRONMENT :**
- platform : win10-64
- GPU: Nvidia Geforce 840M
- tensorflow-gpu 1.1.0 <pip>
- Keras 2.1.1 <pip>
- python 3.5.2 0
- numpy 1.12.1 <pip>
- opencv3 3.1.0 py35_0 menpo
- scikit-learn 0.19.0 np112py35_0
- scipy 1.0.0 <pip>
 ---
- h5py 2.7.1 <pip>
- hdf5 1.10.1 h98b8871_1 anaconda
- eventlet 0.21.0 <pip>
- Flask 0.12.2 <pip>
- greenlet 0.4.12 <pip>
- h5py 2.7.1 <pip>
- hdf5 1.10.1 h98b8871_1 anaconda
- imageio 2.1.2 <pip>

**Comment by davisjazz** [comment]
**# TRACE:**
```
(keras) C:\BehavioralCloning>python model04_171201-1104.py
Using TensorFlow backend.

train_lines = 6428, validation_lines = 1608

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lambda_1 (Lambda)            (None, 160, 320, 3)       0
_________________________________________________________________
cropping2d_1 (Cropping2D)    (None, 65, 320, 3)        0
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 31, 158, 24)       1824
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 77, 36)        21636
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 5, 37, 48)         43248
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 3, 35, 64)         27712
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 1, 33, 64)         36928
_________________________________________________________________
dropout_1 (Dropout)          (None, 1, 33, 64)         0
_________________________________________________________________
flatten_1 (Flatten)          (None, 2112)              0
_________________________________________________________________
dense_1 (Dense)              (None, 100)               211300
_________________________________________________________________
dense_2 (Dense)              (None, 50)                5050
_________________________________________________________________
dense_3 (Dense)              (None, 10)                510
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 11
=================================================================
Total params: 348,219
Trainable params: 348,219
Non-trainable params: 0
_________________________________________________________________
Epoch 1/10
Traceback (most recent call last):
  File "model04_171201-1104.py", line 132, in <module>
    initial_epoch   = 0 )
  File "C:\Anaconda3\envs\keras\Lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda3\envs\keras\Lib\site-packages\keras\models.py", line 1223, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Anaconda3\envs\keras\Lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda3\envs\keras\Lib\site-packages\keras\engine\training.py", line 2114, in fit_generator
    class_weight=class_weight)
  File "C:\Anaconda3\envs\keras\Lib\site-packages\keras\engine\training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "C:\Anaconda3\envs\keras\Lib\site-packages\keras\engine\training.py", line 1407, in _standardize_user_data
    exception_prefix='input')
  File "C:\Anaconda3\envs\keras\Lib\site-packages\keras\engine\training.py", line 141, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking input: expected lambda_1_input to have 4 dimensions, but got array with shape (192, 1)
```

**Comment by davisjazz** [comment]
**# ROOT CAUSE: DRIVING_LOG.CSV** 
The problem came from the file driving_log.csv.
The image paths were not updated with the right location.

**# FIX:**
1. open driving_log.csv in Excel
2. replace all 'IMG/' by 'C:\data\sample\IMG\'
3. save the modifications

**Comment by davisjazz** [comment]
**# ROOT CAUSE: DRIVING_LOG.CSV** 
The problem came from the file driving_log.csv.
The image paths were not updated with the right location.

**# FIX:**
1. open driving_log.csv in Excel
2. replace all 'IMG/' by 'C:\data\sample\IMG\'
3. save the modifications
