### ISSUE TITLE
[35b6f77][171202-1726] Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object

### ISSUE THREAD

**Issue by davisjazz** [davisjazz/SDC_PRJ03_Cloning#3]
**# REF :** 35b6f77

**# PREREQUISITE:**
. f07_model_171202-1726.py
. f07_tools_171202-1726.py

**# SCENARIO :**
1.  [win10][cmd] activate keras 
2.  [win10][cmd] python f07_model_171202-1726.py

**# EXPECTED RESULT:**   
- data should be preprocessed successfully
- successful compilation of the model
- generation of the model.h5 file, ready to be tested in the simulator

**# CURRENT RESULT:**
- Compilation failed. The following error message is displayed:   
`43/44 [============================>.] - ETA: 1s - loss: 0.0273Epoch 00001: val_loss improved from inf to 0.05205, saving model to C:/ckpt_W_171202_1948_01_0.05.hdf5   
44/44 [==============================] - 60s 1s/step - loss: 0.0268 - val_loss: 0.0520
Epoch 2/2   
43/44 [============================>.] - ETA: 0s - loss: 0.0043Epoch 00002: val_loss improved from 0.05205 to 0.04469, saving model to C:/ckpt_W_171202_1948_02_0.04.hdf5    
44/44 [==============================] - 29s 670ms/step - loss: 0.0043 - val_loss: 0.0447   
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000002237852F588>>    
Traceback (most recent call last):
  File "C:\Anaconda3\envs\keras\Lib\site-packages\tensorflow\python\client\session.py", line 587, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_NewStatus'`

**# ENVIRONMENT :**
- platform : win10-64
- GPU: Nvidia Geforce 840M
- tensorflow-gpu 1.1.0 <pip>
- Keras 2.1.1 <pip>
- python 3.5.2 0
- numpy 1.12.1 <pip>
- opencv3 3.1.0 py35_0 menpo
- scikit-learn 0.19.0 np112py35_0
- scipy 1.0.0 <pip>
 ---
- h5py 2.7.1 <pip>
- hdf5 1.10.1 h98b8871_1 anaconda
- eventlet 0.21.0 <pip>
- Flask 0.12.2 <pip>
- greenlet 0.4.12 <pip>
- h5py 2.7.1 <pip>
- hdf5 1.10.1 h98b8871_1 anaconda
- imageio 2.1.2 <pip>

**Comment by davisjazz** [comment]
**# TRACE:**   

`
Using TensorFlow backend.
_________________________________________________________________
Layer (type)                 Output Shape              Param 
=================================================================
lambda_1 (Lambda)            (None, 160, 320, 3)       0
_________________________________________________________________
cropping2d_1 (Cropping2D)    (None, 65, 320, 3)        0
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 31, 158, 24)       1824
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 77, 36)        21636
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 5, 37, 48)         43248
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 3, 35, 64)         27712
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 1, 33, 64)         36928
_________________________________________________________________
dropout_1 (Dropout)          (None, 1, 33, 64)         0
_________________________________________________________________
flatten_1 (Flatten)          (None, 2112)              0
_________________________________________________________________
dense_1 (Dense)              (None, 100)               211300
_________________________________________________________________
dense_2 (Dense)              (None, 50)                5050
_________________________________________________________________
dense_3 (Dense)              (None, 10)                510
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 11
=================================================================
Total params: 348,219
Trainable params: 348,219
Non-trainable params: 0
_________________________________________________________________
Epoch 1/2
2017-12-02 19:48:50.340228: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-12-02 19:48:50.340348: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-02 19:48:50.341803: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-02 19:48:50.343174: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-02 19:48:50.343386: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-02 19:48:50.344937: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-12-02 19:48:50.345474: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-02 19:48:50.345933: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-12-02 19:48:50.990067: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:887] Found device 0 with properties:
name: GeForce 840M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:04:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-12-02 19:48:50.990188: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:908] DMA: 0
2017-12-02 19:48:50.991865: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:918] 0:   Y
2017-12-02 19:48:50.992241: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 840M, pci bus id: 0000:04:00.0)
43/44 [============================>.] - ETA: 1s - loss: 0.0273Epoch 00001: val_loss improved from inf to 0.05205, saving model to C:/ckpt_W_171202_1948_01_0.05.hdf5
44/44 [==============================] - 60s 1s/step - loss: 0.0268 - val_loss: 0.0520
Epoch 2/2
43/44 [============================>.] - ETA: 0s - loss: 0.0043Epoch 00002: val_loss improved from 0.05205 to 0.04469, saving model to C:/ckpt_W_171202_1948_02_0.04.hdf5
44/44 [==============================] - 29s 670ms/step - loss: 0.0043 - val_loss: 0.0447
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000002237852F588>>
Traceback (most recent call last):
  File "C:\Anaconda3\envs\keras\Lib\site-packages\tensorflow\python\client\session.py", line 587, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_NewStatus'
`

**Comment by davisjazz** [comment]
[fixed][f07][171202-2117][debug][issue3] f07_tools_171202-2117,  …
. issue: #3
. note: restart from f06_, add code about random brightness, add random flipping

. test: ok
