### ISSUE TITLE
[3fffbea][f17][180117-2201] TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by davisjazz** [davisjazz/SDC_PRJ03_Cloning#8]
**# REF :** 3fffbea

**# PY FILES :**
. path: '_01_WIP\_Coding_\_4_new code archi'
. f17_newModel_180117-2201.py
. f17_newTool_180117-2201.py

**# SCENARIO :**
1.  [win10][cmd] activate keras 
2.  [win10][cmd] python f17_newModel_180117-2201.py

**# CURRENT RESULT:**   
Epoch 1/10
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\mo\home\_INSTALL_\Anaconda3\envs\keras\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\mo\home\_INSTALL_\Anaconda3\envs\keras\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mo\home\_INSTALL_\Anaconda3\envs\keras\Lib\site-packages\keras\utils\data_utils.py", line 630, in data_generator_task
    generator_output = next(self._generator)
  File "C:\Users\mo\home\_eSDC2_\_PRJ03_\_2_WIP\_171126-1433_BehavioralCloning\newTool.py", line 51, in generator
    augmented_image = image[70:-25, :, :]    # (65,320,3)
TypeError: 'NoneType' object is not subscriptable

Traceback (most recent call last):
  File "newModel.py", line 152, in <module>
    main()
  File "newModel.py", line 148, in main
    history = model_train(args, model, train_lines, validation_lines)
  File "newModel.py", line 116, in model_train
    validation_steps = len(validation_lines)
  File "C:\Users\mo\home\_INSTALL_\Anaconda3\envs\keras\Lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\mo\home\_INSTALL_\Anaconda3\envs\keras\Lib\site-packages\keras\models.py", line 1223, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\mo\home\_INSTALL_\Anaconda3\envs\keras\Lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\mo\home\_INSTALL_\Anaconda3\envs\keras\Lib\site-packages\keras\engine\training.py", line 2083, in fit_generator
    generator_output = next(output_generator)
StopIteration

**# ENVIRONMENT :**
- platform : win10-64
- GPU: Nvidia Geforce 840M
- tensorflow-gpu 1.1.0 <pip>
- Keras 2.1.1 <pip>
- python 3.5.2 0
- numpy 1.12.1 <pip>
- opencv3 3.1.0 py35_0 menpo
- scikit-learn 0.19.0 np112py35_0
- scipy 1.0.0 <pip>
 ---
- h5py 2.7.1 <pip>
- hdf5 1.10.1 h98b8871_1 anaconda
- eventlet 0.21.0 <pip>
- Flask 0.12.2 <pip>
- greenlet 0.4.12 <pip>
- h5py 2.7.1 <pip>
- hdf5 1.10.1 h98b8871_1 anaconda
- imageio 2.1.2 <pip>

**Comment by davisjazz** [comment]
**# REF :** 9a5a54c  

**# PY FILES :**
. path: '_01_WIP\_Coding_\_4_new code archi'
. f17_newModel_180118-1241.py
. f17_newTool_180118-1241.py

**# ROOT CAUSE:**
. The wrong path has been defined in the f17_newTool_180118-1241.py file: 'myDebug/' instead of 'sample/'

**# SOLUTION:**
. There are two options:
1. [cmd] python f17_newModel_180118-1241.py -dir myDebug
or
2. replace 'sample/' by 'myDebug/' in f17_newModel_180118-1241.py file
